# set server to run on the perticular port
server:
  port: 8080
  
spring: 
  datasource:
    url: jdbc:mysql://mysql:3306/cna?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
   
  application:
    name: product-service   
    
eureka:  instance:    prefer-ip-address: true
  client:    service-url:      defaultZone: http://eureka-server:8761/eureka